---

- service:
    name: gerrit
    module: rallyci.services.gerrit2
    fetch: https://review.openstack.org/gitweb?p={project}.git;a=blob_plain;f={path};hb={commit}
    ssh:
      hostname: review.openstack.org
      username: CHANGEME
      keys: ["/etc/rally-ci/rally"]

- service:
    name: status
    module: rallyci.services.status
    listen: ["localhost", "8080"]

- provider:
    name: my_lxc
    module: rallyci.providers.lxc
    hosts:
      - hostname: 10.1.1.1
        port: 16622
    backingstore: zfs
    images:
      ubuntu-1510-py35-dev:
        template: ubuntu
        args: -r wily
        build-scripts: ["install-py35-dev"]

- runner:
    name: lxc
    provider: my_lxc
    module: rallyci.runners.ssh
    logs: /tmp/ci

- job:
    name: pytest
    env:
      PYTEST_PATH: tests/unit
    runner:
      name: lxc
      vms:
        - name: ubuntu-1510-py35-dev
          scripts:
            - git_checkout
            - run_pytest
          publish:
            - ["/tmp/report.html", ""]

- script:
    name: run_pytest
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      cd $PROJECT
      pip install .
      pytest -n auto --html=/tmp/report.html $PYTEST_PATH

- runner:
    name: main
    provider: my_virsh
    module: rallyci.runners.ssh
    logs: /tmp/ci

- script:
    name: init_ubuntu_dev
    interpreter: /bin/bash -xe -s
    data: |
      apt-get -y update && apt-get -y upgrade && apt-get -y install git
      apt-get -y remove cloud-init
      mkdir /etc/skel/.ssh
      cp /root/.ssh/authorized_keys /etc/skel/.ssh/
      useradd -m rally
      echo 'rally ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/rally-42

- script:
    name: clone_projects
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      mkdir openstack-dev
      cd openstack-dev
      git clone git://git.openstack.org/openstack-dev/ci-sandbox.git

- script:
    name: git_checkout
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      cd $GERRIT_PROJECT && git checkout master && git pull
      git fetch https://review.openstack.org/$GERRIT_PROJECT $GERRIT_REF
      git checkout FETCH_HEAD && git rebase master || true
      git clean -fxd -e .tox -e *.egg-info
      git diff --name-only master

- script:
    name: run_tests
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      env && ls
      cd $GERRIT_PROJECT
      git status
      echo "All ok"

- job:
    name: test
    env:
      RCI_TOX_ENV: py27
    runner:
      name: main
      vms:
        - name: noop
        - name: dev
          scripts: ["git_checkout", "run_tests"]
          scp:
            - ["/var/log/", "varlog"]
        - name: dev
          scripts: ["git_checkout", "run_tests"]

- project:
    name: openstack-dev/ci-sandbox
    jobs:
      - test
