---

- ssh-key:
    name: default
    public: "/home/eye/.ssh/test.pub"
    private: "/home/eye/.ssh/test"

- service:
    name: gerrit
    fake-stream: resources/gerrit-sample-stream.json
    module: rallyci.services.gerrit
    cfg-url-template: https://review.openstack.org/gitweb?p={project}.git;a=blob_plain;f=.rally-ci.yaml;hb={commit}
    cr-url-template: https://review.openstack.org/#q,{commit},n,z
    commit-url-template: http://git.openstack.org/cgit/{project}/commit/?id={commit}
    silent: true
    env:
      GERRIT_PROJECT: change.project
      GERRIT_REF: patchSet.ref
      GERRIT_REFUPD_NEW: refUpdate.newRev
      GERRIT_REFUPD_OLD: refUpdate.oldRev
      GERRIT_REFUPD_NAME: refUpdate.refName
      GERRIT_REFUPD_PROJECT: refUpdate.project
    ssh:
      hostname: review.openstack.org
      username: CHANGEME
      keys: ["path_to_private_key"]

- service:
    name: status
    module: rallyci.services.status
    listen: ["0.0.0.0", "8080"]

- provider:
    name: my_virsh
    module: rallyci.providers.virsh
    hosts:
      - hostname: 192.168.1.15
        username: root
    storage:
      backend: zfs
      path: /tank/ci
      dataset: tank/ci
    network:
      private-interface: eth0
      vlan-ranges: "100-900"
    images:
      bare_u1510:
        url: https://cloud-images.ubuntu.com/wily/current/wily-server-cloudimg-amd64-disk1.img
      bare_u1404:
        url: http://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
      u1404:
        parent: bare_u1404
        build-scripts: ["init_ubuntu_dev"]
    vms:
      ubuntu-1404-dev:
        image: u1404

- script:
    name: run_pytest
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      cd $PROJECT
      pip install .
      pytest -n auto --html=/tmp/report.html $PYTEST_PATH

- script:
    name: init_ubuntu_dev
    interpreter: /bin/bash -xe -s
    data: |
      apt-get -y update && apt-get -y upgrade && apt-get -y install git
      apt-get -y remove cloud-init
      mkdir /etc/skel/.ssh
      cp /root/.ssh/authorized_keys /etc/skel/.ssh/
      useradd -m rally
      echo 'rally ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/rally-42

- script:
    name: clone_projects
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      mkdir openstack-dev
      cd openstack-dev
      git clone git://git.openstack.org/openstack-dev/ci-sandbox.git

- script:
    name: git_checkout
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      cd $GERRIT_PROJECT && git checkout master && git pull
      git fetch https://review.openstack.org/$GERRIT_PROJECT $GERRIT_REF
      git checkout FETCH_HEAD && git rebase master || true
      git clean -fxd -e .tox -e *.egg-info
      git diff --name-only master

- script:
    name: run_tests
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      env && ls
      cd $GERRIT_PROJECT
      git status
      echo "tox -e${TOX_ENV}"

- job:
    name: tox
    provider: my_virsh
    vms:
      - name: ubuntu-1404-dev
        scripts:
          - git_checkout
          - run_tests

- job:
    parent: tox
    name: tox-pep8
    env:
      TOX_ENV: pep8

- job:
    parent: tox
    name: tox-py27
    env:
      TOX_ENV: py27

- job:
    parent: tox
    name: tox-py34
    env:
      TOX_ENV: py34

- matrix:
    name: tox-jobs
    projects:
      - openstack-dev/ci-sandbox
      - openstack/designate
      - openstack/murano
      - openstack/rally
    jobs:
      - tox-pep8
